
EVENT_MANAGER:RegisterForEvent("SurveyZoneLoad", EVENT_ADD_ON_LOADED, SurveyZone.Events.onLoaded)

EVENT_MANAGER:RegisterForEvent("SurveyZoneLoadScreen", EVENT_PLAYER_ACTIVATED, SurveyZone.Events.onLoadScreen)

EVENT_MANAGER:RegisterForEvent("SurveyZoneMoveItem", EVENT_INVENTORY_SINGLE_SLOT_UPDATE, SurveyZone.Events.onMoveItem)
EVENT_MANAGER:AddFilterForEvent("SurveyZoneMoveItem", EVENT_INVENTORY_SINGLE_SLOT_UPDATE, REGISTER_FILTER_BAG_ID, BAG_BACKPACK)
EVENT_MANAGER:AddFilterForEvent("SurveyZoneMoveItem", EVENT_INVENTORY_SINGLE_SLOT_UPDATE, REGISTER_FILTER_INVENTORY_UPDATE_REASON, INVENTORY_UPDATE_REASON_DEFAULT)
